/*
 * Inventory API
 *
 * This is a sample inventory management server based on the OpenAPI 3.0 specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddCategory",
		strings.ToUpper("Post"),
		"/category",
		AddCategory,
	},

	Route{
		"DeleteCategory",
		strings.ToUpper("Delete"),
		"/category/{id}",
		DeleteCategory,
	},

	Route{
		"GetCategories",
		strings.ToUpper("Get"),
		"/category",
		GetCategories,
	},

	Route{
		"GetCategoryById",
		strings.ToUpper("Get"),
		"/category/{id}",
		GetCategoryById,
	},

	Route{
		"PutCategoryById",
		strings.ToUpper("Put"),
		"/category/{id}",
		PutCategoryById,
	},

	Route{
		"AddContainer",
		strings.ToUpper("Post"),
		"/container",
		AddContainer,
	},

	Route{
		"DeleteContainer",
		strings.ToUpper("Delete"),
		"/container/{id}",
		DeleteContainer,
	},

	Route{
		"GetContainerById",
		strings.ToUpper("Get"),
		"/container/{id}",
		GetContainerById,
	},

	Route{
		"GetContainers",
		strings.ToUpper("Get"),
		"/container",
		GetContainers,
	},

	Route{
		"PutContainerById",
		strings.ToUpper("Put"),
		"/container/{id}",
		PutContainerById,
	},

	Route{
		"AddItem",
		strings.ToUpper("Post"),
		"/item",
		AddItem,
	},

	Route{
		"DeleteItem",
		strings.ToUpper("Delete"),
		"/item/{id}",
		DeleteItem,
	},

	Route{
		"GetItem",
		strings.ToUpper("Get"),
		"/item",
		GetItem,
	},

	Route{
		"GetItemById",
		strings.ToUpper("Get"),
		"/item/{id}",
		GetItemById,
	},

	Route{
		"PutItemById",
		strings.ToUpper("Put"),
		"/item/{id}",
		PutItemById,
	},
}
